name: cv-learning-env
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
  - xformers
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - jupyterlab
  - pyarrow
  - opencv
  - pillow
  - pywavelets
  - imagehash
  - pytorch::pytorch>=
  - pytorch::torchvision
  - pytorch::pytorch-cuda
  - omegaconf
  - torchmetrics
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - scikit-learn
  - pandas
  - pdf2image
  - transformers
  - pytesseract
  - datasets